# Generated by Django 5.1.2 on 2024-10-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_page_created_at_alter_page_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_date',
        ),
    ]
